spring:
  application:
    name: order-service
  config:
    import: optional:configserver:http://localhost:8888
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      properties:
#        spring.json.type.mapping: orderConfirmation:com.popcorn.ecommerce.order.kafka.OrderConfirmation
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 160000000
            readTimeout: 160000000
          rankings-api:
            readTimeout: 160000000
